# Generated by Django 4.2.5 on 2023-09-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_catlog',
            name='genere',
            field=models.CharField(choices=[('FICTION', 'fiction'), ('TRADITIONAL-LITERATURE', 'trafitional'), ('OTHER', 'other'), ('LITERATURE', 'literature'), ('NON-FICTION', 'non-fictinonon')], max_length=255),
        ),
    ]
